### ISSUE TITLE
VirusTotal Detection?

### ISSUE THREAD

**Issue by Hyperbo7** [priyanshu9588/seesh-gen#3]
https://www.virustotal.com/gui/file/5d10c18a4a3210165c1cd19b35db146339dbfaaca9e2207894d23e76ad91f152/detection
Might be not a virus but maybe it is? :)

**Comment by Snowwy1337** [comment]
It is, it drops 10+ files and contacts 2 ips, which I'm pretty sure is hosting the RAT.

**Comment by Hyperbo7** [comment]
> It is, it drops 10+ files and contacts 2 ips, which I'm pretty sure is hosting the RAT.

Let's report this scammerkid.

**Comment by priyanshu9588** [comment]
have u all listened about api ever its that only i use hwid verification that's why there is the ip if you all don't wanna use then fuck off I don't force you to do that so.
